/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package country.local.Reporting.dbo.queries;

/**
 *
 * @author ctorrest
 */
public class TicketHomeQuery {

    private final String ini_date;
    private final String end_date;

    public String getSetUp() {
        return "SELECT ate.IdAtencion, cli.NomCliente + ' ' + cli.ApeCliente AS Paciente, CASE cli.IdSexo WHEN 1 THEN 'Masculino' WHEN 2 THEN 'Femenino' END AS Genero, '      ' AS Codigo_CIE10, '                                                                                                            ' AS Diagnostico, ate.FecIngreso AS Fecha_Ingreso, NULL \n"
                + "                  AS Fecha_Probable_Salida, '        ' AS CodCama, hcePersonal.Nompersonal + ' ' + hcePersonal.ApePersonal AS Medico_Tratante, ate.FecEgreso AS Fecha_Egreso, NULL AS DiasPostergacion, NULL AS Causal, NULL AS Usuario, NULL \n"
                + "                  AS Fecha_Registro, CASE WHEN datediff(yyyy, fecNacimiento, fecIngreso) = 0 THEN CONVERT(varchar, datediff(mm, fecNacimiento, fecIngreso))+' '+'Meses' ELSE CONVERT(varchar,datediff(yyyy, fecNacimiento, fecIngreso)) END AS Edad\n"
                + "into #temppac\n"
                + "FROM     genUbicacion INNER JOIN\n"
                + "                  admAtencion AS ate ON genUbicacion.IdUbicacion = ate.IdUbicacionActual INNER JOIN\n"
                + "                  admAtencionTipo ON ate.IdAtencionTipo = admAtencionTipo.IdAtencionTipo INNER JOIN\n"
                + "                  admCliente AS cli ON ate.IdCliente = cli.IdCliente INNER JOIN\n"
                + "                  admServicio ON ate.IdServicio = admServicio.IdServicio INNER JOIN\n"
                + "                  hcePersonal ON ate.IdMedico = hcePersonal.IdPersonal\n"
                + "WHERE  (admAtencionTipo.IdAtencionTipo = 9) AND (ate.FecIngreso >= '2019-04-10') AND (ate.IdAtencion IN\n"
                + "                      (SELECT hceConsulta.IdAtencion\n"
                + "                       FROM      hceConsulta WITH (NOLOCK) INNER JOIN\n"
                + "                                         hceConsulDiagnostico WITH (NOLOCK) ON hceConsulDiagnostico.IdConsulta = hceConsulta.IdConsulta INNER JOIN\n"
                + "                                         admAtencion ON hceConsulta.IdAtencion = admAtencion.IdAtencion INNER JOIN\n"
                + "                                         genDiagnostico ON hceConsulDiagnostico.IdDiagnostico = genDiagnostico.IdDiagnostico LEFT OUTER JOIN\n"
                + "                                         hceDiagEstancia AS DE ON DE.IdDiagnostico = hceConsulDiagnostico.IdDiagnostico\n"
                + "                       WHERE   (admAtencion.FecIngreso >= '2019-04-10') AND (genDiagnostico.CodCie9 IN ('N390', 'J209', 'J219', 'J180', 'J189', 'J210', 'J050', 'J042', 'J040', 'J46', 'J459', 'J450', 'J458', 'J451', 'J980', 'J00', 'J108', 'H669', 'B002', 'J101', 'H650', 'J039', \n"
                + "                                         'B340', 'J029', 'J205', 'H659', 'J018', 'J030', 'J158', 'J22', 'J019', 'H700', 'J014', 'K121', 'J36', 'A09', 'A084', 'R11', 'E86', 'K529', 'A049', 'A060', 'A069')))) AND (ate.IdAtencion NOT IN\n"
                + "                      (SELECT DISTINCT traz.IdAtencion\n"
                + "                       FROM      hceTrazaFechaSalida AS traz INNER JOIN\n"
                + "                                         ASI_USUA AS au ON au.cod_usua = traz.CodUsuarioReg INNER JOIN\n"
                + "                                         admCliente AS cli ON cli.IdCliente = traz.IdCliente INNER JOIN\n"
                + "                                         genDiagnostico AS dia ON dia.IdDiagnostico = traz.idDiagnostico INNER JOIN\n"
                + "                                         admAtencion AS ate ON ate.IdAtencion = traz.IdAtencion INNER JOIN\n"
                + "                                         genUbicacion ON ate.IdUbicacionActual = genUbicacion.IdUbicacion INNER JOIN\n"
                + "                                         admAtencionTipo ON ate.IdAtencionTipo = admAtencionTipo.IdAtencionTipo INNER JOIN\n"
                + "                                         admServicio ON ate.IdServicio = admServicio.IdServicio INNER JOIN\n"
                + "                  admCama AS admCama_1 ON ate.IdCamaActual = admCama_1.IdCama \n"
                + "LEFT OUTER JOIN\n"
                + "                                         hceJustificacionFecSalida AS jus ON jus.idTrazaFechaSalida = traz.Id LEFT OUTER JOIN\n"
                + "                                         hceCausalFechaSalida AS cau ON cau.IdCausal = jus.idCausal INNER JOIN\n"
                + "                                         hcePersonal ON ate.IdMedico = hcePersonal.IdPersonal\n"
                + "                       WHERE   (ate.FecEgreso IS NULL))) AND (DATEDIFF(mm, cli.FecNacimiento, ate.FecIngreso) > 1)\n"
                + "\n"
                + "\n"
                + "update  #temppac\n"
                + "set CodCama=a.codcama \n"
                + "from (SELECT  a.IdAtencion, admCama.CodCama\n"
                + "FROM     (SELECT MAX(IdCamaMovimiento) AS IdCamaMovimiento, IdAtencion\n"
                + "                  FROM      admCamaMovimiento\n"
                + "                  GROUP BY IdAtencion) AS a INNER JOIN\n"
                + "                  admCamaMovimiento AS admCamaMovimiento_1 ON a.IdCamaMovimiento = admCamaMovimiento_1.IdCamaMovimiento INNER JOIN\n"
                + "                  admCama ON admCamaMovimiento_1.IdCama = admCama.IdCama AND admCamaMovimiento_1.IdCama = admCama.IdCama) as a\n"
                + " where #temppac.IdAtencion=a.IdAtencion\n"
                + "\n"
                + "update  #temppac\n"
                + "set Codigo_CIE10=a.CodCie9,Diagnostico=a.NomDiagnostico \n"
                + "from(SELECT distinct hceConsulta.IdAtencion,CodCie9,NomDiagnostico\n"
                + "FROM     hceConsulta WITH (NOLOCK) INNER JOIN\n"
                + "                  hceConsulDiagnostico WITH (NOLOCK) ON hceConsulDiagnostico.IdConsulta = hceConsulta.IdConsulta INNER JOIN\n"
                + "                  admAtencion ON hceConsulta.IdAtencion = admAtencion.IdAtencion INNER JOIN\n"
                + "                  genDiagnostico ON hceConsulDiagnostico.IdDiagnostico = genDiagnostico.IdDiagnostico LEFT OUTER JOIN\n"
                + "                  hceDiagEstancia AS DE ON DE.IdDiagnostico = hceConsulDiagnostico.IdDiagnostico\n"
                + "WHERE admAtencion.FecIngreso>='2019-04-10' and  genDiagnostico.CodCie9 IN ('N390', 'J209', 'J219', 'J180', 'J189', 'J210', 'J050', 'J042', 'J040', 'J46', 'J459', 'J450', 'J458', 'J451', 'J980', 'J00', 'J108', 'H669', 'B002', 'J101', 'H650', 'J039', 'B340', 'J029', 'J205', 'H659', 'J018', 'J030', 'J158', 'J22', 'J019', 'H700', \n"
                + "                                         'J014', 'K121', 'J36', 'A09', 'A084', 'R11', 'E86', 'K529', 'A049', 'A060', 'A069' ))as a\n"
                + "where #temppac.IdAtencion=a.IdAtencion\n"
                + "\n"
                + "select IdAtencion,Paciente,Genero,Codigo_CIE10,Diagnostico,Fecha_Ingreso, Fecha_Probable_Salida,\n"
                + "CodCama,Medico_Tratante,Fecha_Egreso,DiasPostergacion,''as Causal\n"
                + ",'' as Usuario,Fecha_Registro,Edad , CONVERT (VARCHAR(4),'') as codCie1, CONVERT (VARCHAR(255),'')  as nomDiagnostico1 \n"
                + ",CONVERT (VARCHAR(4),'')  as codCie2, CONVERT (VARCHAR(255),'') as nomDiagnostico2\n"
                + ",CONVERT (VARCHAR(4),'') as codCie3, CONVERT (VARCHAR(255),'') as nomDiagnostico3\n"
                + ",CONVERT (VARCHAR(4),'') as codCie4, CONVERT (VARCHAR(255),'') as nomDiagnostico4\n"
                + ",CONVERT (VARCHAR(4),'')  as codCie5, CONVERT (VARCHAR(255),'') as nomDiagnostico5\n"
                + ",CONVERT (VARCHAR(4),'')  as codCie6, CONVERT (VARCHAR(255),'') as nomDiagnosticoEgreso\n"
                + ",CONVERT (VARCHAR(2),'')  as Uci\n"
                + "into #temppac1\n"
                + "from #temppac where idatencion not in(	 SELECT distinct  traz.IdAtencion\n"
                + "FROM     hceTrazaFechaSalida AS traz INNER JOIN\n"
                + "                  ASI_USUA AS au ON au.cod_usua = traz.CodUsuarioReg INNER JOIN\n"
                + "                  admCliente AS cli ON cli.IdCliente = traz.IdCliente INNER JOIN\n"
                + "                  genDiagnostico AS dia ON dia.IdDiagnostico = traz.idDiagnostico INNER JOIN\n"
                + "                  admAtencion AS ate ON ate.IdAtencion = traz.IdAtencion INNER JOIN\n"
                + "                  genUbicacion ON ate.IdUbicacionActual = genUbicacion.IdUbicacion INNER JOIN\n"
                + "                  admAtencionTipo ON ate.IdAtencionTipo = admAtencionTipo.IdAtencionTipo INNER JOIN\n"
                + "                  admServicio ON ate.IdServicio = admServicio.IdServicio \n"
                + " INNER JOIN\n"
                + "                  admCama AS admCama_1 ON ate.IdCamaActual = admCama_1.IdCama\n"
                + " LEFT OUTER JOIN\n"
                + "                  hceJustificacionFecSalida AS jus ON jus.idTrazaFechaSalida = traz.Id \n"
                + " LEFT OUTER JOIN\n"
                + "                  hceCausalFechaSalida AS cau ON cau.IdCausal = jus.idCausal\n"
                + " inner join hcePersonal on ate.IdMedico=hcePersonal.IdPersonal\n"
                + "  )\n"
                + "\n"
                + "SELECT DISTINCT \n"
                + "                  traz.IdAtencion, cli.NomCliente + ' ' + cli.ApeCliente AS Paciente, CASE genero WHEN 1 THEN 'Masculino' WHEN 2 THEN 'Femenino' END AS Genero, dia.CodCie9 AS Codigo_CIE10, dia.NomDiagnostico AS Diagnostico, \n"
                + "                  ate.FecIngreso AS Fecha_Ingreso, convert (datetime ,traz.FechaProbableSal,121) AS Fecha_Probable_Salida, \n"
                + " admCama_1.CodCama, hcePersonal.Nompersonal + ' ' + hcePersonal.ApePersonal AS Medico_Tratante, ate.FecEgreso AS Fecha_Egreso, \n"
                + "                  jus.DiasPostergacion, cau.Descripcion AS Causal\n"
                + " , au.nom_usua AS Usuario, traz.FechaRegistro AS Fecha_Registro, CASE WHEN datediff(yyyy, fecNacimiento, fecIngreso) = 0 THEN CONVERT(varchar, datediff(mm, fecNacimiento, \n"
                + "                  fecIngreso)) + ' ' + 'Meses' ELSE CONVERT(varchar, datediff(yyyy, fecNacimiento, fecIngreso)) END AS Edad, CONVERT (VARCHAR(4),'') as codCie1, CONVERT (VARCHAR(255),'')  as nomDiagnostico1 \n"
                + ",CONVERT (VARCHAR(4),'')  as codCie2, CONVERT (VARCHAR(255),'') as nomDiagnostico2\n"
                + ",CONVERT (VARCHAR(4),'') as codCie3, CONVERT (VARCHAR(255),'') as nomDiagnostico3\n"
                + ",CONVERT (VARCHAR(4),'') as codCie4, CONVERT (VARCHAR(255),'') as nomDiagnostico4\n"
                + ",CONVERT (VARCHAR(4),'')  as codCie5, CONVERT (VARCHAR(255),'') as nomDiagnostico5\n"
                + ",CONVERT (VARCHAR(4),'')  as codCie6, CONVERT (VARCHAR(255),'') as nomDiagnosticoEgreso\n"
                + ",CONVERT (VARCHAR(2),'')  as Uci\n"
                + "into #temppac0\n"
                + "FROM     hceTrazaFechaSalida AS traz WITH (nolock) INNER JOIN\n"
                + "                  ASI_USUA AS au WITH (nolock) ON au.cod_usua = traz.CodUsuarioReg INNER JOIN\n"
                + "                  admCliente AS cli WITH (nolock) ON cli.IdCliente = traz.IdCliente INNER JOIN\n"
                + "                  genDiagnostico AS dia WITH (nolock) ON dia.IdDiagnostico = traz.idDiagnostico INNER JOIN\n"
                + "                  admAtencion AS ate WITH (nolock) ON ate.IdAtencion = traz.IdAtencion INNER JOIN\n"
                + "                  genUbicacion WITH (nolock) ON ate.IdUbicacionActual = genUbicacion.IdUbicacion INNER JOIN\n"
                + "                  admAtencionTipo WITH (nolock) ON ate.IdAtencionTipo = admAtencionTipo.IdAtencionTipo INNER JOIN\n"
                + "                  admServicio WITH (nolock) ON ate.IdServicio = admServicio.IdServicio INNER JOIN\n"
                + "                  admCama WITH (nolock) ON traz.Cama = admCama.IdCama LEFT OUTER JOIN\n"
                + "                  hceJustificacionFecSalida AS jus ON jus.idTrazaFechaSalida = traz.Id LEFT OUTER JOIN\n"
                + "                  hceCausalFechaSalida AS cau ON cau.IdCausal = jus.idCausal INNER JOIN\n"
                + "                  hcePersonal ON ate.IdMedico = hcePersonal.IdPersonal INNER JOIN\n"
                + "                  admCama AS admCama_1 ON ate.IdCamaActual = admCama_1.IdCama\n"
                + "ORDER BY traz.IdAtencion asc\n"
                + "\n"
                + "SELECT DISTINCT TOP (100) PERCENT a.IdAtencion, a.idDiagEpicrisis, a.IdPrincipal, b.codCie9, b.nomDiagnostico\n"
                + "into #diag\n"
                + "FROM   (SELECT estadistica.dbo.hceDiagEpicrisis.IdAtencion, estadistica.dbo.hceDiagEpicrisis.idDiagEpicrisis, estadistica.dbo.hceDiagEpicrisis.IdPrincipal\n"
                + "FROM   estadistica.dbo.hceDiagEpicrisis INNER JOIN\n"
                + "             admAtencion ON estadistica.dbo.hceDiagEpicrisis.IdAtencion = admAtencion.idAtencion where admAtencion.IdAtencion in(select distinct idatencion from #temppac0\n"
                + "union all\n"
                + "select idatencion from #temppac1)\n"
                + "             UNION ALL\n"
                + "             SELECT hceInstEgreso.IdAtencion, hceInstEgreso.idDiagEgreso, 1 AS IdPrincipal\n"
                + "FROM   hceInstEgreso INNER JOIN\n"
                + "             admAtencion ON hceInstEgreso.IdAtencion = admAtencion.idAtencion where admAtencion.IdAtencion in(select distinct idatencion from #temppac0\n"
                + "union all\n"
                + "select idatencion from #temppac1)\n"
                + ") AS a INNER JOIN\n"
                + "             genDiagnostico AS b ON b.idDiagnostico = a.idDiagEpicrisis INNER JOIN\n"
                + "             estadistica.dbo.Atenciones AS c ON c.idAtencion = a.IdAtencion INNER JOIN\n"
                + "             admAtencionTipo AS d ON d.idAtencionTipo = c.idAtencionTipo\n"
                + "WHERE (d.idAtenTipoBase <> 1) AND (a.idDiagEpicrisis <> 0)\n"
                + "UNION ALL\n"
                + "SELECT DISTINCT TOP (100) PERCENT a.IdAtencion, a.idDiagnostico, a.IdPrincipal, b.CodCie9, b.nomDiagnostico\n"
                + "FROM   (SELECT estadistica.dbo.hceAtenDiagnosticos.idAtencion, estadistica.dbo.hceAtenDiagnosticos.idDiagnostico, 0 AS IdPrincipal\n"
                + "FROM   estadistica.dbo.hceAtenDiagnosticos INNER JOIN\n"
                + "             admAtencion ON estadistica.dbo.hceAtenDiagnosticos.idAtencion = admAtencion.idAtencion where admAtencion.IdAtencion in (select distinct idatencion from #temppac0\n"
                + "union all\n"
                + "select idatencion from #temppac1)\n"
                + "             UNION ALL\n"
                + "             SELECT estadistica.dbo.hceConsultaEgreso.idAtencion, estadistica.dbo.hceConsultaEgreso.idDiagPrincipal, 0 AS IdPrincipal\n"
                + "FROM   estadistica.dbo.hceConsultaEgreso INNER JOIN\n"
                + "             admAtencion ON estadistica.dbo.hceConsultaEgreso.idAtencion = admAtencion.idAtencion where admAtencion.idatencion in (select distinct idatencion from #temppac0\n"
                + "union all\n"
                + "select idatencion from #temppac1)\n"
                + "             UNION ALL\n"
                + "             SELECT dbo.hceCxCirugia.IdAtencion, dbo.hceCxDiagnostico.IdDiagnostico, dbo.hceCxDiagnostico.IndPpal\n"
                + "             FROM   dbo.hceCxDiagnostico INNER JOIN\n"
                + "                          dbo.hceCxCirugia ON dbo.hceCxDiagnostico.IdCx = dbo.hceCxCirugia.IdCx) AS a INNER JOIN\n"
                + "             dbo.genDiagnostico AS b ON b.idDiagnostico = a.idDiagnostico INNER JOIN\n"
                + "             estadistica.dbo.Atenciones AS c ON c.idAtencion = a.IdAtencion INNER JOIN \n"
                + "             dbo.admAtencionTipo AS d ON d .idAtencionTipo = c.idAtencionTipo INNER JOIN\n"
                + "                 (SELECT DISTINCT TOP (100) PERCENT a.IdAtencion, a.idDiagEpicrisis\n"
                + "                 FROM    (SELECT estadistica.dbo.hceDiagEpicrisis.IdAtencion, estadistica.dbo.hceDiagEpicrisis.idDiagEpicrisis, estadistica.dbo.hceDiagEpicrisis.IdPrincipal\n"
                + "FROM   estadistica.dbo.hceDiagEpicrisis INNER JOIN\n"
                + "             admAtencion ON estadistica.dbo.hceDiagEpicrisis.IdAtencion = admAtencion.idAtencion where admAtencion.idatencion in(select distinct idatencion from #temppac0\n"
                + "union all\n"
                + "select idatencion from #temppac1)\n"
                + "                               UNION ALL\n"
                + "                               SELECT hceInstEgreso.IdAtencion, hceInstEgreso.idDiagEgreso, 1 AS IdPrincipal\n"
                + "FROM   hceInstEgreso INNER JOIN\n"
                + "             admAtencion ON hceInstEgreso.IdAtencion = admAtencion.idAtencion where admAtencion.idatencion in (select distinct idatencion from #temppac0\n"
                + "union all\n"
                + "select idatencion from #temppac1)\n"
                + "  ) AS a INNER JOIN\n"
                + "                              dbo.genDiagnostico AS b ON b.idDiagnostico = a.idDiagEpicrisis INNER JOIN\n"
                + "                              estadistica.dbo.Atenciones AS c ON c.idAtencion = a.IdAtencion INNER JOIN\n"
                + "                              dbo.admAtencionTipo AS d ON d .idAtencionTipo = c.idAtencionTipo\n"
                + "                 WHERE (d .idAtenTipoBase <> 1) AND (a.idDiagEpicrisis <> 0)) AS f ON a.idAtencion = f.IdAtencion AND a.idDiagnostico <> f.idDiagEpicrisis\n"
                + "WHERE (d .idAtenTipoBase <> 1) AND (a.idDiagnostico <> 0)\n"
                + "\n"
                + "SELECT DISTINCT IdAtencion, 0 as IdPrincipal,idDiagEpicrisis,  codCie9, nomDiagnostico\n"
                + "into #diag1\n"
                + "FROM         [#diag]\n"
                + "\n"
                + "update #diag1\n"
                + "set IdPrincipal= a.IdPrincipal from ( select IdAtencion,idDiagEpicrisis,IdPrincipal from #diag where IdPrincipal=1 )as a\n"
                + "where #diag1.IdAtencion=a.IdAtencion and #diag1.idDiagEpicrisis=a.idDiagEpicrisis\n"
                + "\n"
                + "SELECT A.* INTO #TMP_GRD1\n"
                + "FROM\n"
                + "(\n"
                + "SELECT    ROW_NUMBER() OVER(PARTITION BY hdt .IdAtencion ORDER BY hdt .IdPrincipal desc)AS Num, hdt.IdAtencion, hdt .idDiagEpicrisis, hdt.IdPrincipal, hdt.codCie9, hdt.nomDiagnostico\n"
                + "FROM         #diag1 as hdt inner join #temppac1 on hdt .IdAtencion= #temppac1.idatencion\n"
                + ")as A\n"
                + "\n"
                + "update #temppac1\n"
                + "set #temppac1.codCie1=#TMP_GRD1.codCie9,#temppac1.nomDiagnostico1=#TMP_GRD1.nomDiagnostico\n"
                + "from #TMP_GRD1\n"
                + "where #temppac1.idatencion=#TMP_GRD1.idatencion and #TMP_GRD1.num=1 and #TMP_GRD1.idprincipal=1\n"
                + "\n"
                + "update #temppac1\n"
                + "set #temppac1.codCie2=#TMP_GRD1.codCie9,#temppac1.nomDiagnostico2=#TMP_GRD1.nomDiagnostico\n"
                + "from #TMP_GRD1\n"
                + "where #temppac1.idatencion=#TMP_GRD1.idatencion and #TMP_GRD1.num=2\n"
                + "\n"
                + "update #temppac1\n"
                + "set #temppac1.codCie3=#TMP_GRD1.codCie9,#temppac1.nomDiagnostico3=#TMP_GRD1.nomDiagnostico\n"
                + "from #TMP_GRD1\n"
                + "where #temppac1.idatencion=#TMP_GRD1.idatencion and #TMP_GRD1.num=3\n"
                + "\n"
                + "update #temppac1\n"
                + "set #temppac1.codCie4=#TMP_GRD1.codCie9,#temppac1.nomDiagnostico4=#TMP_GRD1.nomDiagnostico\n"
                + "from #TMP_GRD1\n"
                + "where #temppac1.idatencion=#TMP_GRD1.idatencion and #TMP_GRD1.num=4\n"
                + "\n"
                + "update #temppac1\n"
                + "set #temppac1.codCie5=#TMP_GRD1.codCie9,#temppac1.nomDiagnostico5=#TMP_GRD1.nomDiagnostico\n"
                + "from #TMP_GRD1\n"
                + "where #temppac1.idatencion=#TMP_GRD1.idatencion and #TMP_GRD1.num=5\n"
                + "\n"
                + "SELECT A.* INTO #TMP_GRD2\n"
                + "FROM\n"
                + "(\n"
                + "SELECT   distinct  ROW_NUMBER() OVER(PARTITION BY hdt .IdAtencion ORDER BY hdt .IdPrincipal desc)AS Num, hdt.IdAtencion, hdt .idDiagEpicrisis, hdt.IdPrincipal, hdt.codCie9, hdt.nomDiagnostico\n"
                + "FROM         #diag1 as hdt inner join #temppac0 on hdt .IdAtencion= #temppac0.idatencion\n"
                + ")as A\n"
                + "\n"
                + "update #temppac0\n"
                + "set #temppac0.codCie1=#TMP_GRD2.codCie9,#temppac0.nomDiagnostico1=#TMP_GRD2.nomDiagnostico\n"
                + "from #TMP_GRD2\n"
                + "where #temppac0.idatencion=#TMP_GRD2.idatencion and #TMP_GRD2.num=1 and #TMP_GRD2.idprincipal=1\n"
                + "\n"
                + "update #temppac0\n"
                + "set #temppac0.codCie2=#TMP_GRD2.codCie9,#temppac0.nomDiagnostico2=#TMP_GRD2.nomDiagnostico\n"
                + "from #TMP_GRD2\n"
                + "where #temppac0.idatencion=#TMP_GRD2.idatencion and #TMP_GRD2.num=2\n"
                + "\n"
                + "update #temppac0\n"
                + "set #temppac0.codCie3=#TMP_GRD2.codCie9,#temppac0.nomDiagnostico3=#TMP_GRD2.nomDiagnostico\n"
                + "from #TMP_GRD2\n"
                + "where #temppac0.idatencion=#TMP_GRD2.idatencion and #TMP_GRD2.num=3\n"
                + "\n"
                + "update #temppac0\n"
                + "set #temppac0.codCie4=#TMP_GRD2.codCie9,#temppac0.nomDiagnostico4=#TMP_GRD2.nomDiagnostico\n"
                + "from #TMP_GRD2\n"
                + "where #temppac0.idatencion=#TMP_GRD2.idatencion and #TMP_GRD2.num=4\n"
                + "\n"
                + "update #temppac0\n"
                + "set #temppac0.codCie5=#TMP_GRD2.codCie9,#temppac0.nomDiagnostico5=#TMP_GRD2.nomDiagnostico\n"
                + "from #TMP_GRD2\n"
                + "where #temppac0.idatencion=#TMP_GRD2.idatencion and #TMP_GRD2.num=5\n"
                + "\n"
                + "SELECT hceInstEgreso.IdAtencion, hceInstEgreso.idDiagEgreso, 1 AS IdPrincipal, genDiagnostico.NomDiagnostico, genDiagnostico.CodCie9\n"
                + "into #diaegreso\n"
                + "FROM     hceInstEgreso INNER JOIN\n"
                + "                  admAtencion ON hceInstEgreso.IdAtencion = admAtencion.IdAtencion INNER JOIN\n"
                + "                  genDiagnostico ON hceInstEgreso.idDiagEgreso = genDiagnostico.IdDiagnostico\n"
                + "WHERE  (admAtencion.IdAtencion IN\n"
                + "                      (SELECT DISTINCT IdAtencion\n"
                + "                       FROM      [#temppac0]\n"
                + "  union all\n"
                + "  SELECT  IdAtencion\n"
                + "                       FROM      [#temppac1] \n"
                + "  ))\n"
                + "\n"
                + "update  #temppac1\n"
                + "set #temppac1.codCie6=#diaegreso.codCie9,#temppac1.nomDiagnosticoEgreso=#diaegreso.nomDiagnostico\n"
                + "from #diaegreso\n"
                + "where #temppac1.idatencion=#diaegreso.idatencion\n"
                + "\n"
                + "update  #temppac0\n"
                + "set #temppac0.codCie6=#diaegreso.codCie9,#temppac0.nomDiagnosticoEgreso=#diaegreso.nomDiagnostico\n"
                + "from #diaegreso\n"
                + "where #temppac0.idatencion=#diaegreso.idatencion\n"
                + "\n"
                + "update #temppac0\n"
                + "set Uci='Si' from(\n"
                + "select idatencion from admcamamovimiento where idatencion in\n"
                + "(select distinct idatencion from #temppac0\n"
                + "union all\n"
                + "select idatencion from #temppac1) and IdCama in(select idcama from admCama where CodCama like 'U%'))as a\n"
                + "where #temppac0.IdAtencion=a.idatencion\n"
                + "\n"
                + "update #temppac1\n"
                + "set Uci='Si' from(\n"
                + "select idatencion from admcamamovimiento where idatencion in\n"
                + "(select distinct idatencion from #temppac0\n"
                + "union all\n"
                + "select idatencion from #temppac1) and IdCama in(select idcama from admCama where CodCama like 'U%'))as a\n"
                + "where #temppac1.IdAtencion=a.idatencion";
    }

    public String getResult() {
        return String.format("select * \n"
                + "from #temppac0\n"
                + "where Fecha_Ingreso between '%s' and '%s'\n"
                + "union all\n"
                + "select *from #temppac1\n"
                + "where Fecha_Ingreso between '%s' and '%s';",
                ini_date, end_date, ini_date, end_date);
    }

    public String getCleanUp() {
        return "drop table #temppac\n"
                + "drop table #temppac0\n"
                + "drop table #temppac1\n"
                + "drop table #TMP_GRD2\n"
                + "drop table #TMP_GRD1\n"
                + "drop table  #diag1\n"
                + "drop table  #diag;";
    }

    public TicketHomeQuery(String ini_date, String end_date) {
        this.ini_date = ini_date;
        this.end_date = end_date;
    }
}